destination:
  longitude: 130.960005
  latitude: 30.374283333333
threshold:
  # ground
  close_to_goal_distance: 8
  orientation: 7 # the number of degrees to consider the robot is facing the goal

  # img_proc
  red_cone_percent: 30
  cone_not_found: 10
  orientation_ang: 45

