destination:
  longitude: 139.653895
  latitude: 35.951115
threshold:
  # floating
  rised_altitude: 5 #[m]
  landed_altitude: 1 #[m]
  wait_time: 15 #[s]

  # ground
  close_to_goal_distance: 8 #[m]
  orientation: 7 # the number of degrees to consider the robot is facing the goal
  stuck_distance: 0.5 # [m]
  camera_error_distance: 0.5 # [m]

  # img_proc
  far_from_goal_distance: 20 # [m]
  cone_percent: 40 # [%]
  red_cone_percent: 30 # [%]
  cone_not_found: 10 # the number of frames to consider the cone is not found
  orientation_ang: 30 # the adjustment angle of the robot to find the cone

